name: Publish packages (temporary)

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  npm:
    uses: ./.github/workflows/package-npm.yaml
    # uses: tree-sitter/workflows/.github/workflows/package-npm.yml@main
    secrets:
      NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
    with:
      generate: false
      abi-version: "14"
